### ISSUE TITLE
Ginco - Master - Non Ldap authentication 

### ISSUE THREAD

**Issue by ybor** [culturecommunication/ginco#20]
Bonjour,
J'ai bien suivi la documentation d'installation du master Ginco, et cela s'est déroulé correctement.
J'ai pu importer un thesaurus au format skos.
Je rencontre toutefois une  difficulté :  le thésaurus bien qu'importé complètement, la recherche d'un terme ne fonctionne pas. Il y a ces messages dans ginco.log : 
"2014-08-25 15:55:53,073  INFO | http-8080-3 | fr.mcc.ginco.rest.services.Thesaur
usRestService         | thesaurusId = null 
2014-08-25 15:56:13,029 ERROR | http-8080-1 | f.m.g.rest.services.exceptions.Abs
tractExceptionMapper  | Exception in REST services : Search exception 
2014-08-25 15:56:13,356  INFO | http-8080-3 | fr.mcc.ginco.rest.services.Thesaur
usRestService         | Getting Top Languages 
2014-08-25 15:56:13,356  INFO | http-8080-3 | fr.mcc.ginco.rest.services.Thesaur
usRestService         | thesaurusId = null 
2014-08-25 15:56:33,270 ERROR | http-8080-1 | f.m.g.rest.services.exceptions.Abs
tractExceptionMapper  | Exception in REST services : Search exception 
2014-08-25 16:33:32,750 ERROR | http-8080-1 | f.m.g.rest.services.exceptions.Abs".

Auriez-vous une idée de ce qui cloche ( probablement un problème de droit, je suis en non ldap )  ?

Merci d'avance.

**Comment by genmiche** [comment]
Bonjour,

J'ai le même problème : 
 1 / A la connexion sur le compte admin : unable to load user profile 
 2 / A l'indexation SOLR : j'ai le message : 
http://localhost:8080/ginco-admin/services/ui/indexerservice/reindex
{"success":false, "message": "Erreur technique, veuillez contacter un administrateur"}

J'ai installé solr-4.2.1 , j'ai bien /usr/local/solr-4.2.1/ginco/start.jar qui est lancé : 

[root@serveur_ginco]# ps -ef | grep java
tomcat    1165     1  0 09:47 ?        00:01:45 java -Xminf0.1 -Xmaxf0.3 -Dginco-properties=/usr/local/apache-maven-3.0.5/conf/ginco/ -classpath /usr/share/apache-tomcat-6.0.47/bin/bootstrap.jar:/usr/share/apache-tomcat-6.0.47/bin/tomcat-juli.jar:/usr/share/java/commons-daemon.jar -Dcatalina.base=/usr/share/apache-tomcat-6.0.47 -Dcatalina.home=/usr/share/apache-tomcat-6.0.47 -Djava.endorsed.dirs= -Djava.io.tmpdir=/var/cache/tomcat/temp -Djava.util.logging.config.file=/usr/share/apache-tomcat-6.0.47/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager org.apache.catalina.startup.Bootstrap start
root      6981     1  0 14:21 pts/2    00:00:16 java -Xmx1024m -DSTOP.PORT=8079 -DSTOP.KEY=stopkey -jar start.jar
root     10753  6375  0 16:46 pts/0    00:00:00 grep --color=auto java

Merci d'avance pour votre aide.

Cordialement.

**Comment by genmiche** [comment]
Problème  1 résolu , j'ai installé le pilote postgresql-9.2-1004.jdbc4.jar, ginco semble opérationnel.
Il reste le 2ème problème à résoudre.
