### ISSUE TITLE
GINCO ne prend pas en compte les paramètres #ARK Preferences

### ISSUE THREAD

**Issue by etiennemarchand** [culturecommunication/ginco#23]
Bonjour,

J'essaie, comme indiqué par Frédéric Rolland, de mettre à jour le fichier ginco.properties pour que GINCO génère des identifiants ARK propres à l'organisation que j'essaie de mettre en oeuvre. J'ai beau redémarrer tomcat, rien n'y fait, les ark générés sont toujours ceux du MCC, à savoir http://data.culture.fr/thesaurus/resource/ark:/67717/........

J'ai indiqué dans le fichier ginco.properties les paramètres suivants :
#ARK Preferences
application.ark.nma=http://thesaurus.oieau.fr/
application.ark.naan=99160

Malheureusement, ça ne fonctionne pas. Merci d'avance de m'orienter vers la solution, qui j'en suis sur, est connue.

Cordialement.
Etienne

**Comment by fredericrolland** [comment]
Bonjour, 

j'ai demandé à la société chargée de la TMA de me dire ou le bas
blesse. Avez-vous déposé votre message sur Github également ? 

cela peut servir aux autres utilisateurs. 

Merci d'avance, 

cordialement, 

fr 

Le 2015-03-27 15:26, etiennemarchand a écrit : 

> Bonjour, 
> 
> J'essaie, comme indiqué par Frédéric Rolland, de mettre à jour le fichier ginco.properties pour que GINCO génère des identifiants ARK propres à l'organisation que j'essaie de mettre en oeuvre. J'ai beau redémarrer tomcat, rien n'y fait, les ark générés sont toujours ceux du MCC, à savoir http://data.culture.fr/thesaurus/resource/ark:/67717/ [1]........ 
> 
> J'ai indiqué dans le fichier ginco.properties les paramètres suivants :
> #ARK Preferences
> application.ark.nma=http://thesaurus.oieau.fr/ [2]
> application.ark.naan=99160 
> 
> Malheureusement, ça ne fonctionne pas. Merci d'avance de m'orienter vers la solution, qui j'en suis sur, est connue. 
> 
> Cordialement.
> Etienne 
> 
> --
> Reply to this email directly or view it on GitHub [3].
 

Links:
------
[1] http://data.culture.fr/thesaurus/resource/ark:/67717/
[2] http://thesaurus.oieau.fr/
[3] https://github.com/culturecommunication/ginco/issues/23

----------------------------------------------------------------------
Merci de nous aider à préserver l'environnement en n'imprimant ce courriel et les documents joints que si nécessaire.

**Comment by etiennemarchand** [comment]
Bonjour Frédéric,

Oui j'ai posé ma question sur Github, j'espère que Smile trouvera la 
solution rapidement ...

Merci pour votre aide :-)

Etienne MARCHAND
Office International de l'Eau / CNIDE
15 rue Edouard Chamberland
87065 LIMOGES cedex - FRANCE
Tél : 33 (0)5.55.11.47.94
Fax : 33 (0)5.55.11.47.48

**Comment by hufon** [comment]
Avez vous redémarré l'appli après la modification?

**Comment by hufon** [comment]
Je ne reproduis pas ce problème... la configuration doit bien se faire à cet endroit!

**Comment by hufon** [comment]
Le fichier ginco.properties est celui pointé par la variable d'environnement tomcat

**Comment by etiennemarchand** [comment]
Bonjour,

Comment doit s'appeler cette variable d'environnement ?

Etienne MARCHAND
Office International de l'Eau / CNIDE
15 rue Edouard Chamberland
87065 LIMOGES cedex - FRANCE
Tél : 33 (0)5.55.11.47.94
Fax : 33 (0)5.55.11.47.48

**Comment by hufon** [comment]
Cf la documentation: 

-Dginco-properties=${path_to_custom_properties_files} to JAVA_OPTS where "${path_to_custom_properties_files}" is the absolute path to your custom ginco.properties file

**Comment by etiennemarchand** [comment]
Oui cela fonctionne. Nous avions indiqué le chemin du fichier ginco.properties, sans aller jusqu'au nom de fichier lui-même. C'est réparé à présent.
Merci.
Etienne
