### ISSUE TITLE
Affichage Mes / Tous les vocabulaires et Filtrage

### ISSUE THREAD

**Issue by etiennemarchand** [culturecommunication/ginco#25]
Bonjour,

Dans la partie gauche de l'interface de Ginco, dans le menu de navigation, juste au dessus de l'arborescence des vocabulaires / concepts, il y a : 

1/ un interrupteur permettant de choisir entre l'affichage de "mes vocabulaires" ou l'affichage de "tous les vocabulaires". Je pensais que cet affichage dépendait de la liste des utilisateurs affectés à tel vocabulaire et de leur rôle, mais visiblement quiconque est connecté peut voir tous les vocabulaires indépendamment de ses affectations. Pouvez-vous m'expliquer comment fonctionne cet interrupteur d'affichage et comment le paramétrer si cela est possible ? Question corollaire : est-il possible d'interdire à certains utilisateurs la visualisation de certains vocabulaires ? De quelle manière ?

2/ une liste déroulante "Filtrage". Lors de ma formation chez Smile, j'avais noté que cette liste permettait le filtrage par droit (actif pour les responsables opérationnels). Mais cette liste est toujours vide chez moi. Comment ce filtrage fonctionne-t-il ? Comment le paramétrer ?

3/ Il me semble qu'une documentation / wiki  en Dokiel Guide devait être produite. Est-elle à présent disponible ? 

Merci de vos réponses à ces interrogations.
Cordialement.

Etienne

**Comment by KatellBriatte** [comment]
1) Notre philosophie, lors de la création de Ginco, était de favoriser au maximum l'échange et le partage autour des référentiels. Il n'y a donc pas de vocabulaires cachés. Les vocabulaires sont tous accessibles en lecture à tous les utilisateurs identifiés dans notre LDAP, même s'il n'ont aucun rôle sur aucun vocabulaire.

Essayez d'évaluer le besoin d'autres utilisateurs de GINCO pour proposer éventuellement une évolution dans ce sens.

2) Le filtrage se fait sur la valeur contenue dans la métadonnée Auteur du vocabulaire. Suivant l'organisation, on choisira d'y mettre le nom d'un service ou d'une personne (au mcc, nous privilégions le service, les personnes physiques apparaissant dans les contributeurs avec mention de la nature de leur contribution). Il faut savoir que dans la plate-forme de diffusion Ginco-diff, la balise Auteur est utilisée pour faire le filtrage par service producteur, l'URL permet de renvoyer au site du service producteur et le courriel est utilisé dans l'onglet Contact pour envoyer des demandes d'évolution : c'est pourquoi nous privilégions une adresse fonctionnelle et non individuelle.

3) Oui, elle arrive très prochainement (dernière relecture avant validation).
