### ISSUE TITLE
Bizarreries avec un utilisateur Expert ?

### ISSUE THREAD

**Issue by etiennemarchand** [culturecommunication/ginco#26]
Bonjour,

J'ai un thésaurus pour lequel j'ai affecté des utilisateurs déclarés dans l'application, dont certains ont un rôle d'expert. Il se produit les deux comportements (anomalies ?) suivants : 

1/ un utilisateur de rôle expert peut créer une note d'application sur un concept orphelin (statut = Candidat) mais cette note, une fois enregistrée, n'apparaît plus dans les interfaces de n'importe quel utilisateur (expert, responsable opérationnel, administrateur). La note est pourtant bien enregistrée en base de données.

2/ un utilisateur de rôle expert ne peut pas enregistrer une suggestion sur un concept orphelin.

3/ Enfin, quel que soit le rôle de l'utilisateur, la fonctionnalité de liaison de l'arborescence aux onglets ne fonctionne pas.

Merci de vos réponses.
Cordialement.
Etienne

**Comment by KatellBriatte** [comment]
1) je ne reproduis pas ce bogue : j'ai déclaré ma collègue comme expert sur un vocabulaire et lui ai demandé de créer une note d'application sur un concept orphelin candidat. Sa note apparaît bien dans mon interface.
2) je ne reproduis pas ce bogue : la même collègue, toujours en tant qu'expert, m'a adressé une suggestion sur ce même concept orphelin : je retrouve bien sa suggestion dans la liste de mes suggestions.
3) là, c'est un vrai bogue : l'épingle a en effet un fonctionnement assez aléatoire. Je remonte un ticket.
Pour les deux points précédents, pouvez-vous refaire le test ?
