### ISSUE TITLE
L'application ne rend pas la main après une création de concept

### ISSUE THREAD

**Issue by tfrancart** [culturecommunication/ginco#28]
Bonjour

Je viens de réaliser une install de GINCO from scratch grâce à votre bonne documentation. Merci pour ça. Tout semble fonctionner à part un souci : lors de la création d'un nouveau concept, celui-ci est bien créé, bien indexé, mais l'application ne rend pas la main. Après le clic sur "enregistrer", le message qui dit que le concept a bien été créé s'affiche en haut à droite, mais l'écran reste grisé et le message "chargement" ne disparait pas. Le nouveau concept s'affiche bien dans l'arbre et si on double-clic dessus il s'affiche correctement dans un nouvel onglet. Cependant l'onglet dans lequel a été créé le concept ne rend jamais la main. La seule solution est de fermer cet onglet.

![ginco-pb-screenshot](https://cloud.githubusercontent.com/assets/2728945/8432879/f331466a-1f42-11e5-9502-498fd8269992.png)

Le même problème se reproduit sur Firefox et Chrome.
Dans la console du navigateur je ne vois aucun appel réseau en attente, toutes les communications avec le serveur ont répondu correctement.

La création d'un terme, d'un groupe ou d'un tableau de concepts fonctionne correctement. Seule la création d'un concept pose problème.

**Comment by fredericrolland** [comment]
bonjour,
nous n'avons pas ce problème. S'il y a un problème, il doit être visible dans le journal.

**Comment by tfrancart** [comment]
Et moi j'ai ce problème.

Dans le fichier ginco-admin/src/main/webapp/app/controller/ConceptController.js, il y a 2 lignes de code commentées, lignes 850 et 851, dans la fonction appelée lors de la sauvegarde d'un concept :

//me.loadData(theForm, resultRecord);
//theForm.getEl().unmask();

(voir donc ici : https://github.com/culturecommunication/ginco/blob/master/ginco-admin/src/main/webapp/app/controller/ConceptController.js)

"theForm.getEl().unmask();" est l'appel qui "dégrise" et réactive le panneau d'édition du concept, et c'est justement ce qui me fait défaut, tiens tiens...

En décommentant ces 2 lignes, ça marche beaucoup mieux, bizarrement !

Pour info je travaille avec la toute dernière version des sources, build 189ec46f8cb4596c8d082dde13043fe149b12538

**Comment by fredericrolland** [comment]
merci pour cette info. Je le signale à l'équipe en charge de la maintenance pour avoir une correction au plus vite.

**Comment by tfrancart** [comment]
(à restester et valider par eux, bien sûr - j'imagine que ces lignes n'ont pas été commentées sans raison).

**Comment by hufon** [comment]
Ok, je reproduis le problème (uniquement à la création)...
