### ISSUE TITLE
Lors de la création d'un alignement vers un concept GINCO, ce serait bien de pouvoir chercher/sélectionner plutôt que resaisir l'identifiant

### ISSUE THREAD

**Issue by tfrancart** [culturecommunication/ginco#29]
Bonjour

Lorsque je veux saisir un nouvel alignement vers un concept GINCO, je dois copier-coller son identifiant. Ce serait bien de pouvoir chercher/sélectionner le concept à aligner.

Merci

**Comment by KatellBriatte** [comment]
Dans sa version actuelle, GINCO a été conçu pour réaliser des alignements manuels, totalement sous le contrôle du producteur afin d'en garantir la qualité. En effet, il ne suffit pas de rechercher un concept pour l'aligner : il faut vérifier que sa portée sémantique correspond bien à celle du concept source. Pour cela, il faut au minimum connaître son environnement sémantique dans le vocabulaire source (structuration hiérarchique, équivalents, note d'application et/ou définition).
Nous y réfléchissons pour une prochaine version :-)
