### ISSUE TITLE
Documenter l'ajout de vocabulaires externes (table external_thesaurus) pour les alignements

### ISSUE THREAD

**Issue by tfrancart** [culturecommunication/ginco#30]
Après installation de l'application, la liste des thesaurus externes pour la saisie d'alignements externes est vide. Je ne trouve pas d'interface d'administration qui permette d'alimenter cette liste. Je suppose qu'elle est alimentée par des insertions directes en base. Serait-il possible de documenter cette façon d'ajouter des thesaurus dans cette liste ?

Merci

**Comment by KatellBriatte** [comment]
Oui, c'est cela : la liste s'enrichit au fil des alignements réalisés. C'est une petite facilité qui permet de ne pas avoir à ressaisir le nom et le type du vocabulaire cible.
