### ISSUE TITLE
Permettre la création d'identifiants sans "ark:"

### ISSUE THREAD

**Issue by tfrancart** [culturecommunication/ginco#31]
Bonjour

Dans un souci de réutilisation de GINCO en-dehors du MCC, serait-il possible d'avoir la possibilité de générer les URIs des concepts et des termes sans "ark:". C'est-à-dire seulement avec BASE_URL + UUID ? cela pourrait se faire par le biais du fichier de configuration.

L'idée serait de pouvoir avoir :

http://data.culture.fr/thesaurus/resource/bb11dacb-0573-4284-b625-8ab2aa37f6f4

à la place de

http://data.culture.fr/thesaurus/resource/ark:/67717/bb11dacb-0573-4284-b625-8ab2aa37f6f4

Merci

**Comment by fredericrolland** [comment]
Bonjour,
Effectivement pas actuellement. C'est à prévoir dans les évolutions
