### ISSUE TITLE
Installation without admin rights

### ISSUE THREAD

**Issue by wismill** [culturecommunication/ginco#37]
Hi, I would like to know if the file `INSTALL.md` could be updated to do installation without admin rights, apart of the installation of PostgreSQL and the other dependencies. It would also facilitate the writing of my installation guide for Windows.

**Comment by wismill** [comment]
Hi, I cannot get the VM working and I have difficulties to install with the `INSTALL.md` file. I really would like to test Ginco. Please, could you clarify the procedure of installation?

**Comment by hufon** [comment]
Installation of ginco is not supported on windows (not tested). But feel free to contribute.
The only way to run ginco on windows is to run the VM

**Comment by wismill** [comment]
The VM did not work on Linux (starts but the displayed URL does not work) and I cannot install it on Linux either. The installation guide is somehow confusing and requires admin rights. I will be happy to contribute but it is hopeless if I cannot test it.

**Comment by fredericrolland** [comment]
Hi,
it' s ok on Windows. I have tested it on my professionnal computer whith Windows 7. All the componenrts are compatibles with Windows.

**Comment by wismill** [comment]
@fredericrolland I am very interesting. Could you add a guide dedicated to Windows and based on [the installation guide for Linux](https://github.com/culturecommunication/ginco/blob/master/doc/INSTALL.md)?

**Comment by fredericrolland** [comment]
i can give you my personnal guide but i can't update it frequently. So it is based on the first version. Can you give me your email ?
