### ISSUE TITLE
Erreur : pas de liste visible quand on veut attacher un terme parent

### ISSUE THREAD

**Issue by mlongton** [culturecommunication/ginco#38]
Bonjour,

Mon installation est définie avec la langue "fr-BE" par défaut (fichier ginco.properties).
Pour tester, j'ai créé un vocabulaire dont les langues sont "en-UK", "en-US" et y ai défini des concepts en anglais. Je veux rattacher l'un de ceux-ci à l'autre comme concept parent, mais la fenêtre popup qui s'ouvre ne contient aucun terme.
Quand je regarde le log Postgresql (j'ai activé le logging pour voir les queries exécutés), je remarque le query suivant :

LOG:  execute S_1: BEGIN
LOG:  execute S_33/C_34: select this_.lexicalvalue as y0_, tc1_.identifier as y1_ from thesaurus_term this_ right outer join thesaurus_concept tc1_ on this_.conceptid=tc1_.identifier where this_.conceptid is not null and this_.prefered=$1 and this_.lang=$2 and tc1_.thesaurusid=$3 and not tc1_.identifier=$4 and tc1_.status=$5 order by this_.lexicalvalue asc limit $6
DETAIL:  parameters: $1 = 't', $2 = 'fr-FR', $3 = 'http://data.culture.fr/thesaurus/resource/ark:/67717/d86beec4-63b7-4517-bfee-55c7525eefa0', $4 = 'http://data.culture.fr/thesaurus/resource/ark:/67717/92a5276c-fdc4-4d36-a79e-ba29143ee81d', $5 = '1', $6 = '20'
LOG:  execute S_4: COMMIT

où l'on voit que le système utilise la langue "fr-FR" pour faire sa sélection. Donc avec un tel comportement, il est impossible de définir une struture hiérarchique en une langue autre que fr-FR...

Quelqu'un a-t-il une idée de ce qui n'est pas bon dans ma configuration ou mon installation ?

Merci d'avance pour votre aide.
Marie

**Comment by hufon** [comment]
Je reproduis effectivement le problème.
@fredericrolland : pouvez vous retester et saisir le bug dans mantis?

**Comment by KatellBriatte** [comment]
Fait. Ticket https://mantis.culture.fr/mantis/view.php?id=22943.
kb

Katell Briatte
Chef de projet maîtrise d'ouvrage
Coordinatrice du programme HADOC
tél. 01 40 15 82 25

Le 31/08/2015 13:53, Hubert FONGARNAND a écrit :
>
> Je reproduis effectivement le problème.
> @fredericrolland <https://github.com/fredericrolland> : pouvez vous 
> retester et saisir le bug dans mantis?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/culturecommunication/ginco/issues/38#issuecomment-136349382>.
>

----------------------------------------------------------------------
Merci de nous aider à préserver l'environnement en n'imprimant ce courriel et les documents joints que si nécessaire.

**Comment by fredericrolland** [comment]
corrigé à partir de la version TMA-V2.0.4
