### ISSUE TITLE
Export / Import SKOS de Groupes de concept

### ISSUE THREAD

**Issue by xsimo** [culturecommunication/ginco#41]
Bonjour, 

Pour reproduire le probleme :

1. Creation d'un thesaurus THES1
2. ajout du concept C1 avec son terme preferentiel T1
3. ajout du groupe de concept G1 auquel on ajoute C1
4. export et sauvegarde SKOS de THES1
5. suppression de THES1
6. import de THES1

resultat attendu: THES1 contient C1, T1 et G1
resultat obtenu THES1 ne contient que C1 et T1 mais pas G1

![thes1](https://cloud.githubusercontent.com/assets/2412297/14360596/2b485b50-fcc5-11e5-8bd4-9e0d4eae7432.PNG)

**Comment by xsimo** [comment]
[SKOS_THES1_2016-04-07_13-30-19.rdf.txt](https://github.com/culturecommunication/ginco/files/208891/SKOS_THES1_2016-04-07_13-30-19.rdf.txt)

**Comment by fredericrolland** [comment]
Bonjour,
Les groupes fonctionnent en export mais pas en import en SKOS. Il faut utiliser le format XML Ginco
.
