### ISSUE TITLE
Import - concepts orphelins

### ISSUE THREAD

**Issue by xsimo** [culturecommunication/ginco#43]
Bonjour,

je tente d'importer du skos généré programmatiquement. j'obtiens une erreur car je ne génère pas la propriété skos:hasTopConcept. Quelle est la méthode pour importer des concepts de type "orphelins"

Aussi ai-je pris pour acquis que l'on pouvait importer plus d'un thésaurus à la fois par l'inclusion de plusieurs balise <skos:conceptScheme> dans le même fichier RDF. Me trompai-je ?

**Comment by KatellBriatte** [comment]
Bonjour,
oui, dans Ginco, on ne peut importe qu'un ConceptScheme à la fois.
Cordialement,
kb

Katell Briatte
Cheffe du département des systèmes d'information patrimoniaux
Coordinatrice du programme HADOC
tél. 01 40 15 82 25
mob. 06 76 90 99 92

Le 14/04/2016 16:25, Simon Arame a écrit :
>
> Bonjour,
>
> je tente d'importer du skos généré programmatiquement. j'obtiens une 
> erreur inconnue. je joins à ce billet une copie du fichier de registre 
> de tomcat.
>
> J'ai pris pour acquis que l'on pouvait importer plus d'un thésaurus à 
> la fois par l'inclusion de plusieurs balise skos:conceptScheme dans le 
> même fichier RDF. Me trompai-je ?
>
> Quoiqu'il en soit je vais retenter en limitant à un seul thésaurus par 
> fichier RDF.
>
> Merci.
> catalina.out.tail.log.txt 
> <https://github.com/culturecommunication/ginco/files/219297/catalina.out.tail.log.txt>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/culturecommunication/ginco/issues/43>
>

----------------------------------------------------------------------
Merci de nous aider à préserver l'environnement en n'imprimant ce courriel et les documents joints que si nécessaire.
