### ISSUE TITLE
déploiement ginco-webservice sous tomcat 8 (serveur)

### ISSUE THREAD

**Issue by slindev** [culturecommunication/ginco#45]
Bonjour, je réussi à déployer les 2 war (admin & webservice) sous local avec tomcat 8(window) et ils marchent, mais quand je veux les déployer sous un serveur (ubuntu) : ginco-admin.war est déployer et marche, mais le ginco-webservice.war a une erreur : 
> 
18-May-2016 10:28:58.513 SEVERE [http-nio-8080-exec-23] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ThesaurusService': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.apache.cxf.common.classloader.ClassLoaderUtils.loadClass(Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Class;)Ljava/lang/Class;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1514)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)

J'utilise JVM 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14 sous ubuntu et 1.8.0_91-b14 sous window.
apache tomcat 8.0.32 sous windows et ubuntu. pourriez vous m'aider ? merci.

**Comment by fredericrolland** [comment]
Bonjour,
N'ayant jamais constaté ce problème, je ne peux malheursement pas vous aider
Désolé.
Pourriez-vous événetuellement tester sur une version 1.7 de la JVM ?
Cordialement

**Comment by slindev** [comment]
Bonjour,
je résolu le problème : le problème était le conflit entre 2 libraries sous linux (cxf-api et cxf-common-utilities ) 
>  -->Enlever la dépendance du cxf-common-utilities dans pom.xml et ginco-impl/pom.xml 

> -->Modifier ginco-impl/src/main/java/fr/mcc/ginco/imports/SKOSImportUtils.java  ligne 152
 de `if (StringUtils.isEmpty(skosDate)) {`  à `if (skosDate.isEmpty()) {`  et supprimer l'import org.apache.cxf.common.util.StringUtils;

> -->Même modification pour le fichier  ginco-impl/src/main/java/fr/mcc/ginco/imports ligne 108

>-->Pour être compile sous window, il faut commenter les fonctions de test :  ginco-impl/src/test/java/fr/mcc/ginco/tests/imports/ SKOSImportServiceTest.java et enleve l'import du org.apache.cxf.helpers.IOUtils . sous linux vous aurez besoin de modifier cette fichier (remplacer la fonction IOUTILs.toString par autre chose)

**Comment by clrh** [comment]
@slindev merci, fort contente de trouver ton issue et un contournement ;)
