### ISSUE TITLE
XML Ginco

### ISSUE THREAD

**Issue by ronniemaiden** [culturecommunication/ginco#47]
Bonjour,

Après divers tests sur GINCO, je veux désormais à importer un thesaurus complet dans l'application.
SKOS ne permettant pas de conserver les éléments de gestion, je cherche les spécifications du format XML-Ginco, mais ne trouve rien (je ne vois pas de DTD ou autre...). Où pourrais-je les trouver?

Merci d'avance pour votre aide

**Comment by hufon** [comment]
Bonjour le format d'import/export XML-Ginco sert à l'archivage/sauvegarde des thésaurus Ginco.
Les objets de la BDD sont directement sérialisé en XML. Il n'y a donc pas de DTD ou de schéma, puisqu'il n'est pas fait pour importer des schémas qui viennent de l'exterieur.
