### ISSUE TITLE
Problème ginco "load user profile"

### ISSUE THREAD

**Issue by genmiche** [culturecommunication/ginco#49]
Bonjour,

J'ai le même problème : 
1 / A la connexion sur le compte admin : unable to load user profile 
2 / A l'indexation SOLR : j'ai le message : 
http://localhost:8080/ginco-admin/services/ui/indexerservice/reindex
{"success":false, "message": "Erreur technique, veuillez contacter un administrateur"}

J'ai installé solr-4.2.1 , j'ai bien /usr/local/solr-4.2.1/ginco/start.jar qui est lancé :

[root@serveur_ginco]# ps -ef | grep java
tomcat 1165 1 0 09:47 ? 00:01:45 java -Xminf0.1 -Xmaxf0.3 -Dginco-properties=/usr/local/apache-maven-3.0.5/conf/ginco/ -classpath /usr/share/apache-tomcat-6.0.47/bin/bootstrap.jar:/usr/share/apache-tomcat-6.0.47/bin/tomcat-juli.jar:/usr/share/java/commons-daemon.jar -Dcatalina.base=/usr/share/apache-tomcat-6.0.47 -Dcatalina.home=/usr/share/apache-tomcat-6.0.47 -Djava.endorsed.dirs= -Djava.io.tmpdir=/var/cache/tomcat/temp -Djava.util.logging.config.file=/usr/share/apache-tomcat-6.0.47/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager org.apache.catalina.startup.Bootstrap start
root 6981 1 0 14:21 pts/2 00:00:16 java -Xmx1024m -DSTOP.PORT=8079 -DSTOP.KEY=stopkey -jar start.jar
root 10753 6375 0 16:46 pts/0 00:00:00 grep --color=auto java

Merci d'avance pour votre aide.

Cordialement.

**Comment by genmiche** [comment]
I have a error in ginco.log : 
 "org/postgresql/Driver : Unsupported major.minor version 52.0 "
I'm looking for this error in google and i find the driver  postgresql-9.2-1004.jdbc41.jar , i copy the file in /usr/share/java and reboot but the result is the same.
i have this error in ginco.log : 
"Cannot load JDBC driver class 'org.postgresql.Driver'"

**Comment by genmiche** [comment]
J'ai chargé le pilote postgresql-9.2-1004.jdbc4.jar et l'ai mis en lieu et place du postgresql-9.2-1004.jdbc41.jar : le problème 1 est résolu , il reste le 2ème problème qui reste encore d'actualité.

Si quelqu'un a une idée, je suis preneur.

Cordialement.

**Comment by fredericrolland** [comment]
copie de la configuration :
cp -r /usr/local/apache-maven-3.0.5/conf/ginco/ginco-solr-conf/solr /usr/local/solr-4.2.1/ginco/
Problème résolu.
