### ISSUE TITLE
En tant qu'Utilisateur, je m'authentifie dans l'application sans être dans l'annuaire LDAP.

### ISSUE THREAD

**Issue by tfrancart** [culturecommunication/ginco#6]
Je ne dois pas avoir besoin ni d'installer un serveur LDAP, ni de me connecter à un LDAP existant.

**Comment by xsimo** [comment]
Bonjour, est-ce qu'il est prévu d'accorder des permissions d'écriture par Thésaurus ?

**Comment by KatellBriatte** [comment]
Bonsoir,
si votre question est : est-il possible d'avoir une gestion différenciée des droits par thésaurus dans Ginco, la réponse est oui. En dehors de l'administrateur général, qui a tous les droits sur tout, et du simple utilisateur qui a les droits en lecture sur tout, les autres utilisateurs (responsable opérationnel ou contributeur) sont déclarés par vocabulaire.

**Comment by xsimo** [comment]
Comment alors configurer LDAP pour que l'utilisateur ldap par défaut n'ait accès à rien.

**Comment by fredericrolland** [comment]
l'utilisateur LDAP par défaut n'a accès qu'en lecture aux thesauri.
