### ISSUE TITLE
Ajouter d'autres langues

### ISSUE THREAD

**Issue by anita-mazur** [culturecommunication/ginco#8]
Bonjour,

Comme nous travaillons sur un corpus comportant des langues anciennes, nous aimerions pourvoir choisir des langues comme le latin, hébreu, etc. dans la liste des langues. Que ce soit pour le thésaurus ou les concepts/termes.

Cordialement,
anita mazur

Membre du Pool Biblissima

**Comment by mlongton** [comment]
Bonjour. A quoi servent les colonnes "toplanguage" et "principallanguage" de cette table languages_iso639?
